#!/usr/bin/env python3
"""Connector discovery + gap detector.

Reconciles connectors.json against what is actually reachable on this machine
(MCP servers, gcloud/rclone, env vars, wih-app/.env key NAMES) and writes
connectors/STATUS.md -- which doubles as the credential checklist. Never reads
or prints secret VALUES, only key names. Exit 0 always.
"""
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
REGISTRY = HERE / "connectors.json"
STATUS = HERE / "STATUS.md"
WIH_ENV = Path(r"C:\Users\joshu\wih-app\.env")


def mcp_servers() -> list:
    try:
        out = subprocess.run(["claude", "mcp", "list"], capture_output=True,
                             text=True, timeout=30).stdout or ""
    except Exception:
        return []
    if "No MCP servers" in out:
        return []
    return [l.split(":")[0].strip() for l in out.splitlines() if ":" in l and l.strip()]


def env_key_names() -> set:
    """Names of env vars + wih-app/.env keys (NAMES ONLY, never values)."""
    names = set(os.environ.keys())
    if WIH_ENV.exists():
        for line in WIH_ENV.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                names.add(line.split("=", 1)[0].strip())
    return {n.upper() for n in names}


def have_credential(cred: str, env_names: set) -> bool:
    if not cred:
        return True
    # pull TOKEN/KEY/SID-style identifiers out of the credential_needed text and test them
    tokens = re.findall(r"[A-Z][A-Z0-9_]{3,}", cred.upper())
    return any(t in env_names for t in tokens)


def main() -> int:
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    mcp = mcp_servers()
    env_names = env_key_names()
    have_gcloud = bool(shutil.which("gcloud"))
    have_rclone = bool(shutil.which("rclone"))

    rows, missing = [], []
    for c in reg["connectors"]:
        status = c["status"]
        cred = c.get("credential_needed")
        if status == "active":
            state = "ACTIVE"
        elif status == "manual":
            state = "MANUAL (drop files in)"
        else:  # needs-credentials
            ready = have_credential(cred, env_names)
            # Google connectors can also be satisfied by gcloud/rclone
            if not ready and cred and ("gcloud" in cred.lower() or "rclone" in cred.lower()):
                ready = have_gcloud or have_rclone
            state = "READY TO WIRE (creds detected)" if ready else "NEEDS CREDENTIALS"
            if not ready:
                missing.append((c["name"], cred))
        rows.append((c["name"], c["type"], state, cred or "-"))

    lines = [
        "# Connector Status",
        "",
        f"_Generated by discover_gaps.py on {datetime.now().strftime('%Y-%m-%d %H:%M')}._",
        "",
        f"- MCP servers connected: {', '.join(mcp) if mcp else 'none'}",
        f"- gcloud available: {have_gcloud} | rclone available: {have_rclone}",
        "",
        "| Connector | Type | State | Credential needed |",
        "|---|---|---|---|",
    ]
    for n, t, s, cr in rows:
        lines.append(f"| {n} | {t} | {s} | {cr} |")
    lines += ["", "## To light up the API connectors, provide:"]
    if missing:
        for n, cr in missing:
            lines.append(f"- **{n}** -> {cr}")
    else:
        lines.append("- (nothing outstanding)")
    lines += [
        "",
        "Drop credentials into a `.env` the connectors can read (never commit it; "
        "it must be gitignored), or connect the relevant MCP server. Re-run "
        "`python connectors/discover_gaps.py` to refresh this file.",
        "",
    ]
    STATUS.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {STATUS.name}: {len(rows)} connectors, {len(missing)} need credentials")
    return 0


if __name__ == "__main__":
    sys.exit(main())
